"""empty message

Revision ID: 17add37005c4
Revises: 78b55931dcfc
Create Date: 2024-04-29 12:49:00.673887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17add37005c4'
down_revision = '78b55931dcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('lastname', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=180), nullable=False),
    sa.Column('image', sa.String(length=180), nullable=True),
    sa.Column('speciality', sa.String(length=80), nullable=False),
    sa.Column('calendar', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('rol', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('calendar', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('calendar')
        batch_op.drop_column('rol')
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')
        batch_op.drop_column('nickname')

    op.drop_table('coach')
    # ### end Alembic commands ###
