"""empty message

Revision ID: 716110c5eb32
Revises: 17add37005c4
Create Date: 2024-05-13 17:55:49.179611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716110c5eb32'
down_revision = '17add37005c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('gym', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=180), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('url', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('vip_price', sa.Float(), nullable=True),
    sa.Column('image_product', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=180), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    op.drop_table('club')
    # ### end Alembic commands ###
