"""empty message

Revision ID: 8524b998612e
Revises: cfd20f3b4b89
Create Date: 2024-05-12 11:46:17.259224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8524b998612e'
down_revision = 'cfd20f3b4b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('gym', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=180), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club')
    # ### end Alembic commands ###
